### ISSUE TITLE
Error in  setup 

### ISSUE THREAD

**Issue by azvaska** [fedspendingtransparency/data-act-broker-backend#2292]
hello i followed the readme but once I issued the command 
`docker exec -it dataact-broker-backend python dataactcore/scripts/initialize.py -i ` 

this error pops out:
`2022-04-07 21:34:18,828 INFO:__main__:Loading CFDA Program
2022-04-07 21:34:18,828 INFO:dataactvalidator.scripts.load_cfda_data:Fetching CFDA file from new-url.com/cfda.csv
Traceback (most recent call last):
  File "dataactcore/scripts/initialize.py", line 249, in <module>
    main()
  File "dataactcore/scripts/initialize.py", line 180, in main
    load_domain_value_files(validator_config_path, args.force)
  File "dataactcore/scripts/initialize.py", line 93, in load_domain_value_files
    load_cfda_program(base_path)
  File "/data-act/backend/dataactvalidator/scripts/load_cfda_data.py", line 82, in load_cfda_program
    r = requests.get(S3_CFDA_FILE, allow_redirects=True)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'new-url.com/cfda.csv': No schema supplied. Perhaps you meant http://new-url.com/cfda.csv?
`

**Comment by dpb-bah** [comment]
Hi @azvaska, we keep these fields defaulted `new-url.com` with the intention of having our operation scripts populate them upon deploys as they can change over time. We can update our config examples to use the proper URL but in the meantime, you can use `https://files.usaspending.gov/reference_data` for `usas_public_reference_url` and that should get you going. Apologies for the inconvenience.

**Comment by hotashley** [comment]
This fraud hackers did this

**Comment by dpb-bah** [comment]
This is the Broker application that pulls it from various external sources, some that require credentials and not available to the public. If you want to run USASpending.gov locally, you can download a subset of the database and run the USASpending application locally (https://github.com/fedspendingtransparency/usaspending-api) using that database. If you then want it to always be updated, that won't be possible due to security concerns and lack of access to all of the external systems the broker uses.
